### ISSUE TITLE
NPE at ca.coglinc.gradle.plugins.javacc.NonJavaccSourceFileVisitor.visitFile(NonJavaccSourceFileVisitor.java:21)

### ISSUE THREAD

**Issue by zosrothko** [johnmartel/javaccPlugin#34]
Hi John

Got a NPE when building this project https://github.com/jtb-javacc/SPLJ/tree/NPE-in-javaCCplugin

```
Caused by: java.lang.NullPointerException
        at ca.coglinc.gradle.plugins.javacc.NonJavaccSourceFileVisitor.visitFile(NonJavaccSourceFileVisitor.java:21)
        at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:81)
        at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:54)
        at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker.walkDir(Jdk7DirectoryWalker.java:54)
        at org.gradle.api.internal.file.collections.DirectoryFileTree.walkDir(DirectoryFileTree.java:146)
        at org.gradle.api.internal.file.collections.DirectoryFileTree.visitFrom(DirectoryFileTree.java:130)
        at org.gradle.api.internal.file.collections.DirectoryFileTree.visit(DirectoryFileTree.java:115)
        at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:109)
        at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:58)
        at ca.coglinc.gradle.plugins.javacc.AbstractJavaccTask.copyNonJavaccFilesToOutputDirectory(AbstractJavaccTask.java:58)
        at ca.coglinc.gradle.plugins.javacc.CompileJavaccTask.run(CompileJavaccTask.java:31)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:133)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:126)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:115)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

**Comment by johnmartel** [comment]
I just cloned your repo and cannot reproduce with **Gradle 3.2.1** using `./gradlew clean build`. Again, can you please provide a little more insight into how you got this issue?

**Comment by johnmartel** [comment]
This repo of yours looks a lot like the Interpreter example from javacc. If you look at my fork of the javacc repo, I made the changes to enable building this example with gradle.
